inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/spec_helper.rb'
