version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     ruby: 3.2.1
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t rockolify .
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker tag rockolify:latest ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/rockolify:latest
      - docker push ${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/rockolify:latest
