version: '3'

services:
    redis:
        image: redis:4-alpine
        ports:
            - 3002:6379
    app:
        container_name: backend_server
        image: accifontefranco/democratify_api:latest
        build:
            context: .
            args:
                port: 3001
        environment:
            - CONTAINER=APP
            - DEMOCRATIFYAPI_DATABASE_DB_NAME="${DEMOCRATIFYAPI_DATABASE_DB_NAME}"
            - DEMOCRATIFYAPI_DATABASE_USERNAME="${DEMOCRATIFYAPI_DATABASE_USERNAME}"
            - DEMOCRATIFYAPI_DATABASE_PASSWORD="${DEMOCRATIFYAPI_DATABASE_PASSWORD}"
            - DEMOCRATIFYAPI_DATABASE_HOSTNAME="${DEMOCRATIFYAPI_DATABASE_HOSTNAME}"
            - DEMOCRATIFYAPI_DATABASE_PORT="${DEMOCRATIFYAPI_DATABASE_PORT}"
        depends_on:
            - redis
        ports:
            - 3001:3000
        volumes:
            - .:/home/democratify/app
            - /home/democratify/app/log
        tty: true
        stdin_open: true
        # network_mode: "host"
        command: "bundle exec rails s -p 3000 -b 0.0.0.0 -e production"
