# DEV
version: '3'

services:
    redis:
        image: redis:4-alpine
        ports:
            - 3002:6379
    sidekiq:
        container_name: backend_sidekiq
        image: accifontefranco/democratify_api:latest
        environment:
            - CONTAINER=SIDEKIQ
            - REDIS_HOSTNAME=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        volumes:
            - .:/home/democratify/app
            - /home/democratify/app/log
        # network_mode: "host"
        command: "bundle exec sidekiq -e production -C config/sidekiq.yml"
