
default: &default
  adapter: postgresql
  encoding: unicode
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: democratifyAPI_test
  port: 5432
  host: 0.0.0.0
  username: postgres
